//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMA_Docker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCE_Keywords
    {
        public System.Guid FileID { get; set; }
        public System.Guid UserID { get; set; }
        public string Keyword { get; set; }
        public float Rank { get; set; }
    
        public virtual DCE_Templates DCE_Templates { get; set; }
    }
}
