//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMA_Docker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCE_Templates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DCE_Templates()
        {
            this.DCE_Keywords = new HashSet<DCE_Keywords>();
        }
    
        public System.Guid FileID { get; set; }
        public string Name { get; set; }
        public string DocumentType { get; set; }
        public string VirtualPath { get; set; }
        public System.DateTime DateTimeUploaded { get; set; }
        public string Description { get; set; }
        public System.Guid UserID { get; set; }
        public string DocumentOCRContent { get; set; }
        public string SkipPages { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCE_Keywords> DCE_Keywords { get; set; }
        public virtual File File { get; set; }
    }
}
