//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMA_Docker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.aspnet_Users = new HashSet<aspnet_Users>();
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
            this.TagsOnFiles = new HashSet<TagsOnFile>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string VirtualPath { get; set; }
        public System.DateTime DateTimeUploaded { get; set; }
        public string NiceNameOrAreaName { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual FileBeenOCR FileBeenOCR { get; set; }
        public virtual DCE_Templates DCE_Templates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsOnFile> TagsOnFiles { get; set; }
    }
}
