//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMA_Docker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesDownloadAuditTrail
    {
        public System.Guid FileID { get; set; }
        public string FileName { get; set; }
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateTimeDownloaded { get; set; }
    }
}
