//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMA_Docker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCRFileExtension
    {
        public string FileExtension { get; set; }
        public string Remark { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
    }
}
