//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMA_Docker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleProfile
    {
        public System.Guid UserId { get; set; }
        public System.Guid RoleId { get; set; }
        public string PropertyNames { get; set; }
        public string PropertyValuesString { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
